WebApplicationMVC/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationMVC.ModelsViewData;
using WebApplicationMVC.Service.Services;

namespace WebApplicationMVC.Controllers
{
    public class CadastroController : Controller
    {
        public CadastroService CadastroService { get; set; }

        public CadastroController()
        {
            CadastroService = new CadastroService();
        }


        // GET: Cadastro
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public ActionResult CadastroUsuario(string nome, string email, string confEmail, string senha, string confSenha)
        {
            try
            {
                CadastroService.SalvarUsuario(nome, email, confEmail, senha, confSenha);
                return Redirect(Url.Action("Index", "Login"));
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

WebApplicationMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplicationMVC.ModelsViewData;
using System.Web.Mvc;

namespace WebApplicationMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Certificados()
        {
            return View();
        }

        public ActionResult Sobre()
        {
            return View();
        }
    }
}

WebApplicationMVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationMVC.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public ActionResult Index()
         {
            return View();
        }

        [HttpPost]
        public ActionResult LoginUsuario(string email, string senha)
        {

            return Redirect(Url.Action("Index", "Home"));
        }

    }
}

WebApplicationMVC/Views/Cadastro/Index.cshtml
@model WebApplicationMVC.ModelsViewData.CadastroViewData

<div class="containerCdt">
    <div class="row">
        <div class="cadastro">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="row">
                    <form action="@Url.Action("CadastroUsuario", "Cadastro")" method="post" class="needs-validation" name="cadastro" novalidate>
                        <h1>Fazer Cadastro</h1>
                        <div class="form-group row formCad">
                            <label for="txt" class="col-form-label row">Nome da Empresa</label>
                            <div class="col-lg-12 col-md-12  col-sm-12 col-xl-12 col-12 col-form-label">
                                <input type="text" name="nome" class="form-control cad" id="nome" value="" placeholder="Insira o Nome" title="Nome" required>
                                <div class="invalid-feedback">
                                    Por favor, insira o Nome.
                                </div>
                            </div>
                        </div>
                        <div class="form-group row formCad">
                            <label for="txtEmail" class="col-form-label row">E-mail</label>
                            <div class="col-lg-12 col-md-12  col-sm-12 col-xl-12 col-12 col-form-label">
                                <input type="email" name="email" class="form-control cad" id="email" value="" placeholder="Ex: maria@gmail.com" title="Email" required>
                                <div class="invalid-feedback">
                                    Você precisa inserir seu E-mail.
                                </div>
                                <a href="#" id="manual-ajax"></a>
                                <div class="modal">
                                    <p>Emails diferentes!</p>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row formCad">
                            <label for="confEmail" class="col-form-label row">Repetir e-mail</label>
                            <div class="col-lg-12 col-md-12  col-sm-12 col-xl-12 col-12 col-form-label">
                                <input type="email" name="confEmail" class="form-control cad" oninput="validarEmail(this)" id="confEmail" value="" placeholder="Confirme seu e-mail" title="Repetir Email" required>
                                <div class="invalid-feedback">
                                    Por favor, confirme seu E-mail.
                                </div>
                            </div>
                        </div>
                        <div class="form-group row formCad">
                            <label for="validationCustom01" class="col-form-label row">Senha</label>
                            <div class="col-lg-12 col-md-12  col-sm-12 col-xl-12 col-12 col-form-label">
                                <input type="password" class="form-control cad" name="senha" id="senha" value="" placeholder="Crie uma senha" required>
                                <div class="invalid-feedback">
                                    Você precisa criar uma Senha.
                                </div>
                            </div>
                        </div>
                        <div class="form-group row formCad">
                            <label for="validationCustom01" class="col-form-label row">Repetir senha</label>
                            <div class="col-lg-12 col-md-12  col-sm-12 col-xl-12 col-12 col-form-label">
                                <input type="password" class="form-control cad" name="confSenha" id="confSenha" value="" placeholder="Confirme sua senha" required>
                                <div class="invalid-feedback">
                                    Por favor, confirme sua Senha.
                                </div>
                            </div>
                        </div>
                        <div class="btn-cadastro">
                            <button type="submit" id="botaoCad" class="btn btn-primary" onclick="verificaEmail">CADASTRAR</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>





@section scripts{
    <script type="text/javascript">
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                var forms = document.getElementsByClassName('needs-validation');
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
}

WebApplicationMVC/Views/Home/Certificados.cshtml

@model WebApplicationMVC.ModelsViewData.HomeViewData
<div class="homeCertificados">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
        <div class="row">
            <div class="certificados">
                <div class="row">
                    <div class="card um" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_1.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_1.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">Lógica de Programação</h5>
                        </div>
                    </div>
                    <div class="card dois" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_2.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_2.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">HTML 5 Básico</h5>
                        </div>
                    </div>
                    <div class="card tres" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_3.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_3.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">CSS 3 Básico</h5>
                        </div>
                    </div>
                    <div class="card quatro" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_4.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_4.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">C# Básico</h5>
                        </div>
                    </div>
                    <div class="card cinco" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_5.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_5.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">C# Avançado</h5>
                        </div>
                    </div>
                    <div class="card seis" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_6.jpg" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_6.jpg" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">Licenciatura em Ed. Física</h5>
                        </div>
                    </div>
                    <div class="card sete" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_7.jpg" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_7.jpg" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">Bacharelado em Ed. Física</h5>
                        </div>
                    </div>
                    <div class="card oito" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_8.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_8.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">HTML Básico</h5>
                        </div>
                    </div>
                    <div class="card nove" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_9.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_9.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">Espanhol Básico</h5>
                        </div>
                    </div>
                    <div class="card dez" style="width: 200px;height: 200px;">
                        <a href="~/assets/images/card_10.png" title="Clique aqui para ampliar"><img class="card-img-top" src="~/assets/images/card_10.png" alt="Imagem de capa do card" src="link da imagem" width="90" height="90" /></a>
                        <div class="card-body">
                            <h5 class="card-title">Espanhol Intermediário</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplicationMVC/Views/Home/Index.cshtml

@model WebApplicationMVC.ModelsViewData.HomeViewData

<div class="homePage">
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="~/assets/images/DEV.jpeg" alt="Primeiro Slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/assets/images/DEV1.png" alt="Segundo Slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/assets/images/DEV3.jpg" alt="Terceiro Slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Anterior</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Próximo</span>
            </a>
        </div>
    </div>
</div>

WebApplicationMVC/Views/Home/Sobre.cshtml

@model WebApplicationMVC.ModelsViewData.HomeViewData
<div class="homeSobre">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
        <div class="row">
            <div class="cont_sobre">
                <div class="caixaUm_sobre">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <h1 class="titulo_sobre">Dielle de Oliveira Ribeiro</h1>
                        <div class="row">
                            <div class="imagem_sobre">
                                <img src="~/assets/images/Wikipedia.png" style="width: 150px;height: 150px;" />
                            </div>
                            <h1 class="tema_sobre">Biografia</h1>
                            <p class="paragrafo_sobre">
                                Nascida e criada em Brasília, aos 17 anos me mudei para cidade Goiânia onde tive a minha única filha (Ana Beatriz) aos 19 anos de idade.
                                Aos 22 anos consegui uma bolsa de estudos através do Enem no curso que desejava (Licenciatura em Educação Física), agarrei a oportunidade e me formei no ano de 2017 aos 26 anos de idade.
                                Ao me formar percebi que o mercado de trabalho para licenciados era desfavorável e havia uma necessidade de complementar os estudos com um curso de Bacharelado.
                                No mesmo ano decidi investir na minha carreira e me mudei para a cidade do Rio de Janeiro, que é uma cidade mais esportiva. Comecei trabalhar na área e dei início a minha segunda graduação,
                                agora Bacharelado em Educação física. Após dois anos no Rio de Janeiro, percebi que apesar de ser uma grande cidade não há oportunidade de crescimento profissional,
                                foi então que no final do ano de 2019 me mudei pra cidade de São Paulo em busca de oportunidades e crescimento profissional. Chegando em São Paulo comecei trabalhar em uma assessoria esportiva. Infelizmente no começo de 2020 deu início a pandemia do Covid 19 e a empresa dispensou seus professores.
                                Nesse momento decidi que Educação Física não me traria o crescimento profissional que tanto almejava e decidi recomeçar em uma nova carreira. Comecei um trabalho Home Office, para manter as dispesas e no tempo restante comecei estudar inglês, lógica e linguagem de programação.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="caixa_sobre">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="row">
                            <div class="imagem_sobre">
                                <img src="~/assets/images/linguagem.jpg" style="width: 150px;height: 150px;" />
                            </div>
                            <h1 class="tema_sobre">Tecnologias</h1>
                            <ul class="listas_sobre">
                                <li>HTML</li>
                                <li>CSS</li>
                                <li>Bootstrap</li>
                                <li>Media Query</li>
                                <li>Java Script</li>
                                <li>C#</li>
                                <li>.NET Framework</li>
                                <li>MVC</li>
                                <li>SQL Server</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="caixa_sobre">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="row">
                            <div class="imagem_sobre">
                                <img src="~/assets/images/Formacao.jpg" style="width: 150px;height: 150px;" />
                            </div>
                            <h1 class="tema_sobre">Formação Acadêmica</h1>
                            <ul class="listas_sobre list_fomr">
                                <li>2013-2017 - Licenciatura em Educação Física - Pontifícia Universidade Católica de Goiás (PUC-GO).</li>
                                <li>2018-2019 - Bacharelado em Educação Física - Centro Universitário Leonardo Da Vinci (UNIASSELVI).</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="caixa_sobre">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="row">
                            <div class="imagem_sobre">
                                <img src="~/assets/images/Idiomas.jpg" style="width: 150px;height: 150px;" />
                            </div>
                            <h1 class="tema_sobre">Idiomas</h1>
                            <ul class="listas_sobre">
                                <li>Potuguês -Nativo</li>
                                <li>Espanhol - Fluente</li>
                                <li>Inglês - Básico</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="caixa_sobre">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="row">
                            <div class="imagem_sobre">
                                <img src="~/assets/images/Qualidades.png" style="width: 150px;height: 150px;" />
                            </div>
                            <h1 class="tema_sobre">Qualidades</h1>
                            <ul class="listas_sobre">
                                <li>Capacidade Analítica</li>
                                <li>Raciocício Lógico</li>
                                <li>Persistência</li>
                                <li>Foco</li>
                                <li>Dedicação</li>
                                <li>Autodidata</li>
                                <li>Resiliência</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplicationMVC/Views/Login/Index.cshtml
@model WebApplicationMVC.ModelsViewData.LoginViewData

<div class="containerLgn">
    <div class="row">
        <div class="login">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="row">
                    <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                        <div class="row">
                            <div class="image">
                                <img src="~/assets/images/logo.jpg" />
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                        <div class="row">
                            <form action="@Url.Action("LoginUsuario","Login")" method="post" class="formulario">
                                <h1 class="text-center"> Fazer Login</h1>
                                <div class="form-group">
                                    <label for="exampleInputEmail1"></label>
                                    <i class="fas fa-envelope"></i>
                                    <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1"></label>
                                    <i class="fas fa-lock"></i>
                                    <input type="password" class="form-control" name="senha" id="exampleInputPassword1" placeholder="Senha">
                                </div>
                                <div class="btn-login">
                                    <button type="submit" class="btn btn-primary">LOGIN</button>
                                </div>
                                <div class="creat">
                                    <a href="#">Esqueci Usuário/Senha</a>
                                    <a href="#">Crie Sua Conta</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplicationMVC/Views/Shared/_Footer.cshtml
<footer>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
        <div class="row">
            <div class="midia">
                <a class="facebook" href="https://www.facebook.com/greendielle" target="_blank"><i class="fab fa-facebook-square"></i></a>
                <a class="github" href="https://github.com/Diellita" target="_blank"><i class="fab fa-github-square"></i></a>
                <a class="linkedin" href="https://www.linkedin.com/in/dielle-oliveira-ribeiro-6aa822199/" target="_blank"><i class="fab fa-linkedin"></i></a>
                <a class="whatsapp" href="https://whats.link/httpsapiwhatsappcomsendphone5511932009663textolc3a120dielle2c20acabei20de20vizualizar20seu20github" target="_blank"><i class="fab fa-whatsapp"></i></a>
                <a class="email"><i class="far fa-envelope"> prof.dielle@gmail.com</i></a>
            </div>
        </div>
    </div>
</footer>

WebApplicationMVC/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="@Url.Action("Index","Home")">Dielle de Oliveira</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Cadastro")">Cadastro <span class="sr-only">(página atual)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Login")">Login <span class="sr-only">(página atual)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Saiba Mais
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="@Url.Action("Certificados","Home")">Certificados</a>
                    <a class="dropdown-item" href="@Url.Action("Sobre","Home")">Sobre</a>
                </div>
            </li>
        </ul>
    </div>
</nav>















@*<nav class="navbar navbar-toggler navbar-expand-lg navbar-light bg-light navbar-expand{-sm|-md|-lg|-xl}">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Cadastro", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Login", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Sobre", "Contact", "Home", new { area = "" }, new { @class = "navbar-brand" })
    </nav>*@

WebApplicationMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>

    @Html.Partial("_Header")

    <div class="body-content">
        @RenderBody()
        <hr />
    </div>
    
    @Html.Partial("_Footer")



    @RenderSection("scripts", required: false)
</body>
</html>